### ISSUE TITLE
denominator cohort build drill out the ram 

### ISSUE THREAD

**Issue by rfherrerac** [darwin-eu/IncidencePrevalence#5]
**Describe the bug**
When running generateDenominatorCohortSet in a US large dataset in redshift, the memory ram is consumed vastly.  And takes forever

R version 4.2.3 (2023-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux 8.7 (Ootpa)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.15.so

Version 0.4.1 did not have that issue ran pretty fast.

**Comment by edward-burn** [comment]
Thanks for reporting this @rfherrerac, can you share the settings you used with the function and I will investigate this?

**Comment by rfherrerac** [comment]
Thanks @edward-burn  
cdm <- generateDenominatorCohortSet(
  cdm = cdm,
  name = "denominator",
  cohortDateRange = as.Date(c("2018-01-01", "2020-12-31")),#c(lubridate::ymd("2021-01-01"), lubridate::ymd("2023-01-31")),
  ageGroup = list(c(18,44), c(45,64),
                  c(65,74), c(75,100)),
  sex = c("Male", "Female", "Both"),
  daysPriorObservation = 1,
  requirementInteractions=FALSE
)

**Comment by rfherrerac** [comment]
For sure! happy to do so.

**Comment by edward-burn** [comment]
@rfherrerac I'm not seeing anything obvious that I've changed that would of caused this (but I'll keep looking). Can I just check what versions of dbplyr and RPostgres you have installed? I'm just wondering if it might relate to https://github.com/r-dbi/RPostgres/issues/457

**Comment by rfherrerac** [comment]
Hi @edward-burn  I have RPostgres 1.4.6. and dbplyr 2.4.0

**Comment by edward-burn** [comment]
Hmmm @rfherrerac with your current set up could you please try and run 
profvis::profvis({
    cdm <- generateDenominatorCohortSet(
      cdm = cdm,
      name = "denominator"
    ) 
  })
and share a screenshot of the figure it produces?

**Comment by edward-burn** [comment]
Hi @rfherrerac, could you please try with the 0.7 version of IncidencePrevalence that is now out on cran? I realised that a dependency I was using was collecting data into R, and so with this fixed I´m hoping your issue will be solved but would be great if you could confirm

**Comment by rfherrerac** [comment]
Hi @edward-burn, it worked perfectly. Thanks a lot!
